version: 2.1
jobs:
  build:
    docker:
      - image: node:10.16-alpine
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: 'npm ci'
      - run:
          name: 'Setup default configuration and operator'
          command: 'npm run install-mock-config'
      - run:
          name: 'Tests'
          command: 'npm test'